// Experience data file
// This file contains all the work experience information that will be displayed on the website
// Edit this file to update your experience information

export const experience = [
  {
    id: 1,
    title: "POS Operation and Integration Specialist",
    company: "Grubtech",
    location: "Cairo, Egypt",
    period: "01/2024 – Current",
    responsibilities: [
      "Creating and managing all technical setups needed for customers to integrate their online food channels in the system.",
      "Connecting point of sale (POS) systems with all food applications to grow customers' businesses and streamline their operations.",
      "Working closely with the Sales and Customer Success teams to facilitate operations of onboarding new customers.",
      "Anticipating and troubleshooting any issue that may arise during the integration process.",
      "Working in cross-functional projects with Engineering team to address the product issues and areas of improvement, enhancing the integration process and determine user stories."
    ]
  },
  {
    id: 2,
    title: "Regional POS Integration Specialist",
    company: "Talabat",
    location: "Cairo, Egypt",
    period: "07/2023 – 01/2024",
    responsibilities: [
      "Manage the onboarding and switching requests with our partnered integrators and cloud kitchens.",
      "Provide technical support for our partners regarding POS and KDS systems to ensure smooth operations and successful orders.",
      "Analyse and testing of the system's operation and its efficiency to support business functions and deliverables.",
      "Manage the communications with our partners and integrators, and our Engineering team to ensure the POS system's functionality."
    ]
  },
  {
    id: 3,
    title: "Senior Regional Key Account Specialist",
    company: "Talabat",
    location: "Cairo, Egypt",
    period: "02/2020 – 07/2023",
    responsibilities: [
      "Support our key partners in MENA region to manage menu and content related requests, execute marketing campaigns, and provide necessary technical support.",
      "Operate logistics operations with local teams in each country and manage the communications between our company and our stakeholders to ensure our customers satisfaction."
    ]
  },
  {
    id: 4,
    title: "Senior Medical Marketing Representative",
    company: "Kemet Clinical Laboratories",
    location: "Cairo, Egypt",
    period: "11/2017 – 02/2020",
    responsibilities: [
      "Selling the company's services to possible leads, and other relevant healthcare providers.",
      "Scheduling appointments and negotiating contracts.",
      "Building and maintaining good business relationships with customers and following up on leads generated by the company to encourage repeat purchases and improve sales."
    ]
  }
];

